### ISSUE TITLE
TypeError: conn.sendRaw is not a function

### ISSUE THREAD

**Issue by gabhi** [sreeix/redis-proxy#25]
I getting following error 

``TypeError: conn.sendRaw is not a function
    at /usr/local/lib/node_modules/redis-proxy/lib/server.js:60:17
    at take (/usr/local/lib/node_modules/redis-proxy/node_modules/connection_pool/lib/connection_pool.js:53:12)
    at Server.sendCommand (/usr/local/lib/node_modules/redis-proxy/lib/server.js:55:20)
    at RedisProxy.readsToSlaves (/usr/local/lib/node_modules/redis-proxy/lib/redis_proxy.js:105:23)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-proxy/server.js:30:17)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)``

**Comment by gabhi** [comment]
My node configurations are as follows
➜  ~  node --version
v5.4.0
➜  ~  npm --version
3.3.12

**Comment by gabhi** [comment]
@sreeix are you aware about this issue?

**Comment by sreeix** [comment]
Can you just clone the current master and try and see if it works? the npm one is a bit dated and seems like has a wierd condition when raw redis api is not setup before first use.

**Comment by gabhi** [comment]
after cloning i m getting following error

````
➜  redis-proxy git:(master) ✗ npm install

> hiredis@0.4.1 install /Users/agaikwad/git/redis-proxy/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis-c.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/hiredis-c.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/agaikwad/git/redis-proxy/node_modules/hiredis
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON redis-proxy@0.0.7 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/agaikwad/git/redis-proxy/npm-debug.log

````
